#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from relay_tools.client_cli import client_cli
if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(client_cli())
